{% set name = "sinabs" %}
{% set version = "3.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sinabs-{{ version }}.tar.gz
  sha256: 1d17344ddc418631827c00f77256fbc981bdf8b3ff32d2605fd35157677d367b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pbr
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - numpy
    - pbr
    - python >={{ python_min }}
    - pytorch >=1.9.0
    - onnx
    - nir
    - nirtorch
    - matplotlib-base

test:
  requires:
    - python {{ python_min }}
  imports:
    - sinabs
  # Pip checks for proprietary library to be installed
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://pypi.org/project/sinabs/
  summary: SynSense Spiking Neural Network simulator for deep neural networks (DNNs).
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
