{% set name = "sinabs" %}
{% set version = "3.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sinabs-{{ version }}.tar.gz
  sha256: 9cf887ae417332d409ba0cb45111de7da90848b006776bf262c8ff0f2f7234f6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pbr
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - numpy
    - pbr
    - python >={{ python_min }}
    - pytorch >=1.9.0
    - onnx
    - nir
    - nirtorch

test:
  requires:
    - python {{ python_min }}
  imports:
    - sinabs
  # Pip checks for proprietary library to be installed
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://pypi.org/project/sinabs/
  summary: SynSense Spiking Neural Network simulator for deep neural networks (DNNs).
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
