{% set name = "sinabs" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sinabs-{{ version }}.tar.gz
  sha256: 0f47bec66fa73b4edf575ee4f8be15646d6aa91156238dd5579a3871da7bd62e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - sysroot_linux-64 ==2.17                # [linux64]
  host:
    - pbr
    - pip
    - python >=3.6
  run:
    - numpy
    - pbr
    - python >=3.6
    - pytorch >=1.9.0
    - onnx

test:
  imports:
    - sinabs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sinabs/
  summary: SynSense Spiking Neural Network simulator for deep neural networks (DNNs).
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
