{% set name = "sinabs" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sinabs-{{ version }}.tar.gz
  sha256: 28b478b2133ceb94c52e5ddc2d46054e59d14687117eab1aebf9974d3e6eb5f8

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - sysroot_linux-64 ==2.17                # [linux64]
  host:
    - pbr
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - pbr
    - python >={{ python_min }}
    - pytorch >=1.9.0
    - onnx
    - nir
    - nirtorch

test:
  requires:
    - python {{ python_min }}
  imports:
    - sinabs
  # Pip checks for proprietary library to be installed
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://pypi.org/project/sinabs/
  summary: SynSense Spiking Neural Network simulator for deep neural networks (DNNs).
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
